name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
      - uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew shadowJar
